const SETTINGS = {
  WIDTH : 1200,
  HEIGHT : 800,
  BORDER_WIDTH : 10,
  BACKGROUND_COLOR : "#FFFFFF"
};

SETTINGS.CLIENT_SETTINGS = {
  WIDTH : SETTINGS.WIDTH,
  HEIGHT : SETTINGS.HEIGHT,
  BORDER_WIDTH : SETTINGS.BORDER_WIDTH,
  BACKGROUND_COLOR : SETTINGS.BACKGROUND_COLOR
};

module.exports = SETTINGS;